<?php
/*Created by Кирилл (16.08.2018 19:44)*/

return array(
	'books'=>array(
		'level_1'=>'livres',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'editeurs',
			'series'=>'series',
			'authors'=>'ecrivains',
			'bindings'=>'couverture',
			'years'=>'annees',
		),
	),
	'sheetmusic'=>array(
		'level_1'=>'partitions',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'editeurs',
			'series'=>'series',
			'authors'=>'ecrivains',
			'bindings'=>'performance',
			'years'=>'annees',
		),
	),
	'music'=>array(
		'level_1'=>'musique',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'editeurs',
			'series'=>'series',
			'authors'=>'ecrivains',
			'performers'=>'interpretes',
			'media'=>'type-de-porteur',
			'years'=>'annees',
		),
	),
	'soft'=>array(
		'level_1'=>'multimedia',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'editeurs',
			'authors'=>'ecrivains',
			'media'=>'type-de-porteur',
			'years'=>'annees',
		),
	),
	'periodics'=>array(
		'level_1'=>'periodiques',
		'level_2'=>array(
			'categories'=>'categories',
			'types'=>'type-d-edition',
		),
	),
	'video'=>array(
		'level_1'=>'films-en-dvd',
		'level_2'=>array(
			'categories'=>'categories',
			'actors'=>'acteurs',
			'directors'=>'directeurs',
			'audiostreams'=>'pistes-audio',
			'subtitles'=>'langue-des-sous-titres',
			'media'=>'type-de-porteur',
			'years'=>'annees',
		),
	),
	'printed'=>array(
		'level_1'=>'souvenirs',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'fabricants',
			'years'=>'annees',
		),
	),
	'maps'=>array(
		'level_1'=>'cartes',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'editeurs',
			'bindings'=>'performance',
			'years'=>'annees',
		),
	),


	'sale'=>'vente',
	'register'=>'inscription',
	'login'=>'se-connecter',
	'cart'=>'panier',
	'conditions'=>'conditions-d-utilisation',
	'conditions_order'=>'comment-passer-une-commande',
	'conditions_subscription'=>'termes-de-l-ordre-des-periodiques',
	'contact'=>'contacts',
	'legal_notice'=>'avis-legal',
	'faq'=>'il-y-a-une-question',
	'aboutus'=>'a-propos-de-nous',
	'ourstore'=>'notre-boutique',
	'csr'=>'responsabilite',
	'offers_partners'=>'offres-speciales-pour-les-concessionnaires',
	'thawte'=>'informations-sur-thawte',
	'safety'=>'informations-sur-paiements-de-securite',
	'zone_info'=>'zona-5',
	'paypal'=>'quest-ce-que-paypal',
	'sitemap'=>'plan-du-site',
//	''=>'compte',
);