<?php
/*Created by Кирилл (16.08.2018 19:44)*/

return array(
	'books'=>array(
		'level_1'=>'livres',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'editeurs',
			'series'=>'series',
			'authors'=>'ecrivains',
			'bindings'=>'couverture',
			'years'=>'annees',
			'sale'=>'soldes',
		),
	),
	'sheetmusic'=>array(
		'level_1'=>'partitions',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'editeurs',
			'series'=>'series',
			'authors'=>'ecrivains',
			'bindings'=>'format',
			'years'=>'annees',
			'sale'=>'soldes',
		),
	),
	'music'=>array(
		'level_1'=>'musique',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'editeurs',
			'series'=>'series',
			'authors'=>'ecrivains',
			'performers'=>'interpretes',
			'media'=>'type-de-porteur',
			'years'=>'annees',
			'sale'=>'soldes',
		),
	),
	'soft'=>array(
		'level_1'=>'multimedia',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'editeurs',
			'authors'=>'ecrivains',
			'media'=>'type-de-porteur',
			'years'=>'annees',
			'sale'=>'soldes',
		),
	),
	'periodics'=>array(
		'level_1'=>'abonnement',
		'level_2'=>array(
			'categories'=>'categories',
			'types'=>'type-d-edition',
			'gift'=>'en-cadeau',
			'sale'=>'soldes',
		),
	),
	'video'=>array(
		'level_1'=>'films-en-dvd',
		'level_2'=>array(
			'categories'=>'categories',
			'actors'=>'acteurs',
			'directors'=>'directeurs',
			'audiostreams'=>'pistes-audio',
			'subtitles'=>'langue-des-sous-titres',
			'media'=>'type-de-porteur',
			'years'=>'annees',
			'yearreleases'=>'annee-de-sortie',
			'studios'=>'societes-de-production',
			'sale'=>'soldes',
		),
	),
	'printed'=>array(
		'level_1'=>'autre',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'fabricants',
			'years'=>'annees',
			'sale'=>'soldes',
		),
	),
	'maps'=>array(
		'level_1'=>'cartes',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'editeurs',
			'bindings'=>'couverture',
			'years'=>'annees',
			'sale'=>'soldes',
		),
	),


	'sale'=>'vente',
	'register'=>'inscription',
	'login'=>'se-connecter',
	'cart'=>'panier',
	'conditions'=>'conditions-d-utilisation',
	'conditions_order'=>'comment-passer-une-commande',
	'conditions_subscription'=>'termes-de-l-ordre-des-periodiques',
	'contact'=>'contacts',
	'legal_notice'=>'avis-legal',
	'faq'=>'il-y-a-une-question',
	'aboutus'=>'a-propos-de-nous',
	'ourstore'=>'notre-boutique',
	'csr'=>'responsabilite',
	'offers_partners'=>'offres-speciales-pour-les-concessionnaires',
//	'thawte'=>'informations-sur-thawte',
	'safety'=>'informations-sur-paiements-de-securite',
	'zone_info'=>'zona-5',
	'paypal'=>'quest-ce-que-paypal',
	'sitemap'=>'plan-du-site',
	'me'=>'compte',
	'advsearch'=>'chercher',
	'forgot'=>'recuperation-de-mot-de-passe',
	'delivery'=>'expedition',
	'news'=>'nouvelles',
	'certificate'=>'cheque_cadeau',
	'cashbackworld'=>'cashbackworld',


	'offers'=>'recommandations',
	'for-firms'=>'offres-speciales-pour-les-entreprises',
	'for-lib'=>'offres-speciales-pour-les-bibliotheques',
	'for-uni'=>'offres-speciales-pour-les-enseignants',
	'for-fs'=>'offres-speciales-sans-frais-de-port',
	'for-alle2'=>'offres-speciales-pour-2-euro',

	'bookshelf'=>'etagere',
);