<?php
/*Created by Кирилл (16.08.2018 19:44)*/

return array(
	'books'=>array(
		'level_1'=>'libros',
		'level_2'=>array(
			'categories'=>'categorias',
			'publishers'=>'editoriales',
			'series'=>'editoriales',
			'authors'=>'escritores',
			'bindings'=>'portada',
			'years'=>'anos',
		),
	),
	'sheetmusic'=>array(
		'level_1'=>'partituras',
		'level_2'=>array(
			'categories'=>'categorias',
			'publishers'=>'editoriales',
			'series'=>'serie',
			'authors'=>'escritores',
			'bindings'=>'formato',
			'years'=>'anos',
		),
	),
	'music'=>array(
		'level_1'=>'musica',
		'level_2'=>array(
			'categories'=>'categorias',
			'publishers'=>'editoriales',
			'series'=>'serie',
			'authors'=>'escritores',
			'performers'=>'ejecutantes',
			'media'=>'tipo-de-portador',
			'years'=>'anos',
		),
	),
	'soft'=>array(
		'level_1'=>'multimedia',
		'level_2'=>array(
			'categories'=>'categorias',
			'publishers'=>'editoriales',
			'authors'=>'escritores',
			'media'=>'tipo-de-portador',
			'years'=>'anos',
		),
	),
	'periodics'=>array(
		'level_1'=>'suscripcion',
		'level_2'=>array(
			'categories'=>'categorias',
			'types'=>'tipo-de-edicion',
			'gift'=>'como-regalo',
		),
	),
	'video'=>array(
		'level_1'=>'videos-dvd',
		'level_2'=>array(
			'categories'=>'categorias',
			'actors'=>'actores',
			'directors'=>'directores',
			'audiostreams'=>'pistas-de-audio',
			'subtitles'=>'idioma-de-los-subtitulos',
			'media'=>'tipo-de-portador',
			'years'=>'anos',
			'yearreleases'=>'ano-de-lanzamiento',
			'studios'=>'companias-de-produccion',
		),
	),
	'printed'=>array(
		'level_1'=>'otro',
		'level_2'=>array(
			'categories'=>'categorias',
			'publishers'=>'fabricantes',
			'years'=>'anos',
		),
	),
	'maps'=>array(
		'level_1'=>'mapas',
		'level_2'=>array(
			'categories'=>'categorias',
			'publishers'=>'editoriales',
			'bindings'=>'portada',
			'years'=>'anos',
		),
	),


	'sale'=>'venta',
	'register'=>'registro',
	'login'=>'iniciar-sesion',
	'cart'=>'cesta',
	'conditions'=>'terminos-de-uso',
	'conditions_order'=>'kak-sdelat-zakaz',
	'conditions_subscription'=>'terminos-del-orden-de-las-publicaciones-periodicas',
	'contact'=>'contactos',
	'legal_notice'=>'aviso-legal',
	'faq'=>'hay-una-pregunta',
	'aboutus'=>'sobre-nosotros',
	'ourstore'=>'nuestra-tienda',
	'csr'=>'responsabilidad',
	'offers_partners'=>'ofertas-especiales-para-concesionarios',
//	'thawte'=>'informacion-sobre-thawte',
	'safety'=>'informacion-sobre-pagos-de-seguridad',
	'zone_info'=>'zona-5',
	'paypal'=>'que-es-paypal',
	'sitemap'=>'mapa-del-sitio',
	'me'=>'cuenta',
	'advsearch'=>'buscar',
	'forgot'=>'recuperacion-de-contrasena',
	'delivery'=>'delivery',


	'offers'=>'recomendaciones',
	'for-firms'=>'ofertas-especiales-para-empresas',
	'for-lib'=>'ofertas-especiales-para-bibliotecas',
	'for-uni'=>'ofertas-especiales-para-maestros',
	'for-fs'=>'ofertas-especiales-sin-franqueo',
	'for-alle2'=>'ofertas-especiales-por-2-€',

	'bookshelf'=>'estante',

);