<?php
/*Created by Кирилл (16.08.2018 19:44)*/

return array(
	'books'=>array(
		'level_1'=>'books',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'publishers',
			'series'=>'series',
			'authors'=>'authors',
			'bindings'=>'binding',
			'years'=>'years',
			'sale'=>'reduced-prices',
		),
	),
	'sheetmusic'=>array(
		'level_1'=>'sheetmusic',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'publishers',
			'series'=>'series',
			'authors'=>'authors',
			'bindings'=>'format',
			'years'=>'years',
			'sale'=>'reduced-prices',
		),
	),
	'music'=>array(
		'level_1'=>'music',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'labels',
			'series'=>'series',
			'authors'=>'authors',
			'performers'=>'performers',
			'media'=>'product-type',
			'years'=>'years',
			'sale'=>'reduced-prices',
		),
	),
	'soft'=>array(
		'level_1'=>'multimedia',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'publishers',
			'authors'=>'authors',
			'media'=>'product-type',
			'years'=>'years',
			'sale'=>'reduced-prices',
		),
	),
	'periodics'=>array(
		'level_1'=>'subscription',
		'level_2'=>array(
			'categories'=>'categories',
			'types'=>'edition-type',
			'gift'=>'as-a-gift',
			'sale'=>'reduced-prices',
		),
	),
	'video'=>array(
		'level_1'=>'films-on-dvd',
		'level_2'=>array(
			'categories'=>'categories',
			'actors'=>'actors',
			'directors'=>'directors',
			'audiostreams'=>'audio-streams',
			'subtitles'=>'subtitle-language',
			'media'=>'product-type',
			'years'=>'years',
			'yearreleases'=>'release-year',
			'studios'=>'production-companies',
			'sale'=>'reduced-prices',
		),
	),
	'printed'=>array(
		'level_1'=>'other',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'manufacturers',
			'years'=>'years',
			'sale'=>'reduced-prices',
		),
	),
	'maps'=>array(
		'level_1'=>'maps',
		'level_2'=>array(
			'categories'=>'categories',
			'publishers'=>'publishers',
			'bindings'=>'binding',
			'years'=>'years',
			'sale'=>'reduced-prices',
		),
	),


	'sale'=>'sale',
	'register'=>'registration',
	'login'=>'log-in',
	'cart'=>'shopcart',
	'conditions'=>'terms-of-use',
	'conditions_order'=>'how-to-make-an-order',
	'conditions_subscription'=>'terms-of-the-order-of-periodicals',
	'contact'=>'contacts',
	'legal_notice'=>'legal-notice',
	'faq'=>'faq',
	'aboutus'=>'about-us',
	'ourstore'=>'our-store',
	'csr'=>'responsibility',
	'offers_partners'=>'special-offers-for-dealers',
//	'thawte'=>'information-about-thawte',
	'safety'=>'information-about-security-payments',
	'zone_info'=>'zona-5',
	'paypal'=>'what-is-paypal',
	'sitemap'=>'sitemap',
	'me'=>'account',
	'advsearch'=>'search',
	'forgot'=>'password-recovery',
	'delivery'=>'delivery',
	'news'=>'news',
	'certificate'=>'gift_certificate',
	'cashbackworld'=>'cashbackworld',


	'offers'=>'recommendations',
	'for-firms'=>'special-offers-for-companies',
	'for-lib'=>'special-offers-for-libraries',
	'for-uni'=>'special-offers-for-teachers',
	'for-fs'=>'special-offers-without-postage',
	'for-alle2'=>'special-offers-for-2-euro',

	'bookshelf'=>'bookshelf',
);