<?php
/*Created by Кирилл (16.08.2018 19:44)*/

return array(
	'books'=>array(
		'level_1'=>'knigi',
		'level_2'=>array(
			'categories'=>'kategorii',
			'publishers'=>'izdatelstva',
			'series'=>'serii',
		),
	),
	'sheetmusic'=>array(
		'level_1'=>'noty',
		'level_2'=>array(
			'categories'=>'kategorii',
			'publishers'=>'izdatelstva',
			'series'=>'serii',
		),
	),
	'music'=>array(
		'level_1'=>'muzyka',
		'level_2'=>array(
			'categories'=>'kategorii',
			'publishers'=>'leibl',
			'series'=>'serii',
		),
	),
	'soft'=>array(
		'level_1'=>'multimedia',
		'level_2'=>array(
			'categories'=>'kategorii',
			'publishers'=>'izdatelstva',
		),
	),
	'periodics'=>array(
		'level_1'=>'podpiska',
		'level_2'=>array(
			'categories'=>'kategorii',
		),
	),
	'video'=>array(
		'level_1'=>'filmy-na-dvd',
		'level_2'=>array(
			'categories'=>'kategorii',
		),
	),
	'printed'=>array(
		'level_1'=>'suveniry',
		'level_2'=>array(
			'categories'=>'kategorii',
			'publishers'=>'proizvoditeli',
		),
	),
	'maps'=>array(
		'level_1'=>'karty',
		'level_2'=>array(
			'categories'=>'kategorii',
			'publishers'=>'izdatelstva',
		),
	),
);