<?php
/*Created by Кирилл (16.08.2018 19:44)*/

return array(
	'books'=>array(
		'level_1'=>'knigi',
		'level_2'=>array(
			'categories'=>'kategorii',
			'publishers'=>'izdatelstva',
			'series'=>'serii',
			'authors'=>'avtory',
			'bindings'=>'oformlenie',
			'years'=>'goda',
			'sale'=>'po-snizhennym-cenam',
		),
	),
	'sheetmusic'=>array(
		'level_1'=>'noty',
		'level_2'=>array(
			'categories'=>'kategorii',
			'publishers'=>'izdatelstva',
			'series'=>'serii',
			'authors'=>'avtory',
			'bindings'=>'oformlenie',
			'years'=>'goda',
			'sale'=>'po-snizhennym-cenam',
		),
	),
	'music'=>array(
		'level_1'=>'muzyka',
		'level_2'=>array(
			'categories'=>'kategorii',
			'publishers'=>'lejbl',
			'series'=>'serii',
			'authors'=>'avtory',
			'performers'=>'ispolniteli',
			'media'=>'tip-nositelja',
			'years'=>'goda',
			'sale'=>'po-snizhennym-cenam',
		),
	),
	'soft'=>array(
		'level_1'=>'multimedia',
		'level_2'=>array(
			'categories'=>'kategorii',
			'publishers'=>'izdatelstva',
			'authors'=>'avtory',
			'media'=>'tip-nositelja',
			'years'=>'goda',
			'sale'=>'po-snizhennym-cenam',
		),
	),
	'periodics'=>array(
		'level_1'=>'podpiska',
		'level_2'=>array(
			'categories'=>'kategorii',
			'types'=>'tip-izdanija',
			'gift'=>'podarit-podpisku',
			'sale'=>'po-snizhennym-cenam',
		),
	),
	'video'=>array(
		'level_1'=>'filmy-na-dvd',
		'level_2'=>array(
			'categories'=>'kategorii',
			'actors'=>'aktery',
			'directors'=>'rezhissery',
			'audiostreams'=>'zvukovye-dorozhki',
			'subtitles'=>'jazyki-titrov',
			'media'=>'tip-nositelja',
			'years'=>'goda',
			'yearreleases'=>'god-izdanija',
			'studios'=>'studii',
			'sale'=>'po-snizhennym-cenam',
		),
	),
	'printed'=>array(
		'level_1'=>'prochee',
		'level_2'=>array(
			'categories'=>'kategorii',
			'publishers'=>'proizvoditeli',
			'years'=>'goda',
			'sale'=>'po-snizhennym-cenam',
		),
	),
	'maps'=>array(
		'level_1'=>'karty',
		'level_2'=>array(
			'categories'=>'kategorii',
			'publishers'=>'izdatelstva',
			'bindings'=>'oformlenie',
			'years'=>'goda',
			'sale'=>'po-snizhennym-cenam',
		),
	),


	'sale'=>'rasprodazha',
	'register'=>'registracija',
	'login'=>'vhod',
	'cart'=>'korzina',
	'conditions'=>'uslovija-ispolzovanija',
	'conditions_order'=>'kak-sdelat-zakaz',
	'conditions_subscription'=>'uslovija-zakaza-periodiki',
	'contact'=>'kontakty',
	'legal_notice'=>'pravovoe-uvedomlenie',
	'faq'=>'est-vopros',
	'aboutus'=>'o-nas',
	'ourstore'=>'nash-magazin',
	'csr'=>'otvetstvennost',
	'offers_partners'=>'specialnye-predlozhenija-dlja-dilerov',
//	'thawte'=>'informacija-o-thawte',
	'safety'=>'informacija-o-bezopasnosti-platezhej',
	'zone_info'=>'zona-5',
	'paypal'=>'chto-takoe-paypal',
	'sitemap'=>'karta-sajta',
	'me'=>'akkaunt',
	'advsearch'=>'poisk',
	'forgot'=>'vosstanovlenie-parolja',
	'delivery'=>'delivery',
	'news'=>'novosti',
	'certificate'=>'podarochnyj_sertifikat',

	'offers'=>'rekomendatsii',
	'for-firms'=>'specialnye-predlozhenija-dlja-firm',
	'for-lib'=>'specialnye-predlozhenija-dlja-bibliotek',
	'for-uni'=>'specialnye-predlozhenija-dlja-prepodavatelej',
	'for-fs'=>'specialnye-predlozhenija-bez-pochtovyh-rashodov',
	'for-alle2'=>'specialnye-predlozhenija-za-dva-evro',

	'bookshelf'=>'knizhnaja-polka',

);