<?php
/*Created by Кирилл (16.08.2018 19:44)*/

return array(
	'books'=>array(
		'level_1'=>'bocker',
		'level_2'=>array(
			'categories'=>'kategorier',
			'publishers'=>'forlag',
			'series'=>'serier',
			'authors'=>'forfattarna',
			'bindings'=>'omslag',
			'years'=>'ar',
		),
	),
	'sheetmusic'=>array(
		'level_1'=>'noter',
		'level_2'=>array(
			'categories'=>'kategorier',
			'publishers'=>'forlag',
			'series'=>'serier',
			'authors'=>'forfattarna',
			'bindings'=>'format',
			'years'=>'ar',
		),
	),
	'music'=>array(
		'level_1'=>'musik',
		'level_2'=>array(
			'categories'=>'kategorier',
			'publishers'=>'forlag',
			'series'=>'serier',
			'authors'=>'forfattarna',
			'performers'=>'artister',
			'media'=>'format',
			'years'=>'ar',
		),
	),
	'soft'=>array(
		'level_1'=>'multimedia',
		'level_2'=>array(
			'categories'=>'kategorier',
			'publishers'=>'forlag',
			'authors'=>'forfattarna',
			'media'=>'format',
			'years'=>'ar',
		),
	),
	'periodics'=>array(
		'level_1'=>'teckning',
		'level_2'=>array(
			'categories'=>'kategorier',
			'types'=>'typ-av-utgåva',
			'gift'=>'som-gava',
		),
	),
	'video'=>array(
		'level_1'=>'dvd-filmer',
		'level_2'=>array(
			'categories'=>'kategorier',
			'actors'=>'skadespelarna',
			'directors'=>'direktorer',
			'audiostreams'=>'ljudspar',
			'subtitles'=>'undertext-sprak',
			'media'=>'format',
			'years'=>'ar',
			'yearreleases'=>'utgivningsar',
		),
	),
	'printed'=>array(
		'level_1'=>'souvenirer',
		'level_2'=>array(
			'categories'=>'kategorier',
			'publishers'=>'tillverkare',
			'years'=>'ar',
		),
	),
	'maps'=>array(
		'level_1'=>'kartor',
		'level_2'=>array(
			'categories'=>'kategorier',
			'publishers'=>'forlag',
			'bindings'=>'omslag',
			'years'=>'ar',
		),
	),


	'sale'=>'rea',
	'register'=>'registrering',
	'login'=>'logga-in',
	'cart'=>'kundvagn',
	'conditions'=>'anvandarvillkor',
	'conditions_order'=>'hur-man-bestaller',
	'conditions_subscription'=>'villkoren-i-tidskriftsordningen',
	'contact'=>'kontakter',
	'legal_notice'=>'lagligt-meddelande',
	'faq'=>'det-finns-en-fraga',
	'aboutus'=>'om-oss',
	'ourstore'=>'var-butik',
	'csr'=>'ansvar',
	'offers_partners'=>'specialerbjudanden-till-aterforsaljare',
//	'thawte'=>'information-om-thawte',
	'safety'=>'information-om-sakerhetsbetalningar',
	'zone_info'=>'zona-5',
	'paypal'=>'vad-ar-paypal',
	'sitemap'=>'sidokarta',
	'me'=>'konto',
	'advsearch'=>'sok',


	'offers'=>'rekommendationer',
	'for-firms'=>'specialerbjudanden-for-foretag',
	'for-lib'=>'specialerbjudanden-for-bibliotek',
	'for-uni'=>'specialerbjudanden-for-larare',
	'for-fs'=>'specialerbjudanden-utan-porto',
	'for-alle2'=>'specialerbjudanden-for-2-€',

	'bookshelf'=>'bokhylla',
);