<?php
/*Created by Кирилл (16.08.2018 19:44)*/

return array(
	'books'=>array(
		'level_1'=>'bucher',
		'level_2'=>array(
			'categories'=>'kategorien',
			'publishers'=>'verleger',
			'series'=>'serie',
			'authors'=>'schriftsteller',
			'bindings'=>'einband',
			'years'=>'jahr',
		),
	),
	'sheetmusic'=>array(
		'level_1'=>'noten',
		'level_2'=>array(
			'categories'=>'kategorien',
			'publishers'=>'verleger',
			'series'=>'serie',
			'authors'=>'schriftsteller',
			'bindings'=>'format',
			'years'=>'jahr',
		),
	),
	'music'=>array(
		'level_1'=>'musik',
		'level_2'=>array(
			'categories'=>'kategorien',
			'publishers'=>'verleger',
			'series'=>'serie',
			'authors'=>'schriftsteller',
			'performers'=>'darsteller',
			'media'=>'tragertyp',
			'years'=>'jahr',
		),
	),
	'soft'=>array(
		'level_1'=>'multimedia',
		'level_2'=>array(
			'categories'=>'kategorien',
			'publishers'=>'verleger',
			'authors'=>'schriftsteller',
			'media'=>'tragertyp',
			'years'=>'jahr',
		),
	),
	'periodics'=>array(
		'level_1'=>'abonnement',
		'level_2'=>array(
			'categories'=>'kategorien',
			'types'=>'art-der-ausgabe',
			'gift'=>'als-geschenk',
		),
	),
	'video'=>array(
		'level_1'=>'video-dvd',
		'level_2'=>array(
			'categories'=>'kategorien',
			'actors'=>'schauspieler',
			'directors'=>'direktoren',
			'audiostreams'=>'tonspuren',
			'subtitles'=>'untertitel-sprache',
			'media'=>'format',
			'years'=>'jahr',
			'yearreleases'=>'jahr-der-veroffentlichung',
			'studios'=>'produktionsfirmen',
		),
	),
	'printed'=>array(
		'level_1'=>'andere',
		'level_2'=>array(
			'categories'=>'kategorien',
			'publishers'=>'hersteller',
			'years'=>'jahr',
		),
	),
	'maps'=>array(
		'level_1'=>'landkarten',
		'level_2'=>array(
			'categories'=>'kategorien',
			'publishers'=>'verleger',
			'bindings'=>'einband',
			'years'=>'jahr',
		),
	),


	'sale'=>'ausverkauf',
	'register'=>'registrierung',
	'login'=>'einloggen',
	'cart'=>'einkaufskorb',
	'conditions'=>'nutzungsbedingungen',
	'conditions_order'=>'wie-man-eine-bestellung-macht',
	'conditions_subscription'=>'bedingungen-der-reihenfolge-der-zeitschriften',
	'contact'=>'kontakte',
	'legal_notice'=>'rechtlicher-hinweis',
	'faq'=>'da-ist-eine-frage',
	'aboutus'=>'uber-uns',
	'ourstore'=>'unser-geschaft',
	'csr'=>'haftung',
	'offers_partners'=>'spezielle-angebote-fur-handler',
//	'thawte'=>'informationen-uber-thawte',
	'safety'=>'informationen-uber-sicherheitszahlungen',
	'zone_info'=>'zona-5',
	'paypal'=>'was-ist-paypal',
	'sitemap'=>'sitemap',
	'me'=>'konto',
	'advsearch'=>'suche',
	'forgot'=>'passwort-wiederherstellung',
	'delivery'=>'delivery',


	'offers'=>'empfehlungen',
	'for-firms'=>'spezielle-angebote-fur-unternehmen',
	'for-lib'=>'spezielle-angebote-fur-bibliotheken',
	'for-uni'=>'spezielle-angebote-fur-lehrer',
	'for-fs'=>'sonderangebote-ohne-porto',
	'for-alle2'=>'spezielle-angebote-fur-2-€',

	'bookshelf'=>'bucherregal',
);