<?php
/*Created by Кирилл (16.08.2018 19:44)*/

return array(
	'books'=>array(
		'level_1'=>'kirjat',
		'level_2'=>array(
			'categories'=>'kategoriat',
			'publishers'=>'kustantajat',
			'series'=>'sarjat',
			'authors'=>'tekijat',
			'bindings'=>'ulkoasu',
			'years'=>'vuodet',
		),
	),
	'sheetmusic'=>array(
		'level_1'=>'nuotit',
		'level_2'=>array(
			'categories'=>'kategoriat',
			'publishers'=>'kustantajat',
			'series'=>'sarjat',
			'authors'=>'tekijat',
			'bindings'=>'suoritus',
			'years'=>'vuodet',
		),
	),
	'music'=>array(
		'level_1'=>'musiikki',
		'level_2'=>array(
			'categories'=>'kategoriat',
			'publishers'=>'levy-yhtiot',
			'series'=>'sarjat',
			'authors'=>'tekijat',
			'years'=>'vuodet',
			'performers'=>'esiintyjät',
			'media'=>'tuotteen-muoto',
		),
	),
	'soft'=>array(
		'level_1'=>'multimedia',
		'level_2'=>array(
			'categories'=>'luokat',
			'publishers'=>'kustantajat',
			'authors'=>'tekijat',
			'years'=>'vuodet',
			'media'=>'tuotteen-muoto',
		),
	),
	'periodics'=>array(
		'level_1'=>'lehtitilaukset',
		'level_2'=>array(
			'categories'=>'luokat',
			'types'=>'julkaisutyyppi',
		),
	),
	'video'=>array(
		'level_1'=>'dvd-elokuvat',
		'level_2'=>array(
			'categories'=>'luokat',
			'years'=>'vuodet',
			'actors'=>'nayttelijat',
			'directors'=>'ohjaajat',
			'audiostreams'=>'aaniraidat',
			'subtitles'=>'tekstitysten-kieli',
			'media'=>'tuotteen-tyyppi',
		),
	),
	'printed'=>array(
		'level_1'=>'matkamuistoja',
		'level_2'=>array(
			'categories'=>'kategoriat',
			'publishers'=>'valmistajat',
			'years'=>'vuodet',
		),
	),
	'maps'=>array(
		'level_1'=>'kartat',
		'level_2'=>array(
			'categories'=>'kategoriat',
			'publishers'=>'kustantajat',
			'bindings'=>'suoritus',
			'years'=>'vuodet',
		),
	),


	'sale'=>'alennusmyynti',
	'register'=>'rekisterointi',
	'login'=>'kirjaudu-sisaan',
	'cart'=>'ostoskori',
	'conditions'=>'kayttoehdot',
	'conditions_order'=>'kuinka-tehda-tilauksen',
	'conditions_subscription'=>'ehdot-tilaus-aikakauslehdet',
	'contact'=>'yhteystiedot',
	'legal_notice'=>'oikeudellinen-huomautus',
	'faq'=>'kysymys',
	'aboutus'=>'meista',
	'ourstore'=>'myymalamme',
	'csr'=>'vastuu',
	'offers_partners'=>'tarjoukset-jalleenmyyjille',
	'thawte'=>'tietoa-thawtesta',
	'safety'=>'tietoa-maksujen-turvallisuudesta',
	'zone_info'=>'aluekoodi-5',
	'paypal'=>'mika-on-paypal',
	'sitemap'=>'sivustokartta',
//	''=>'tili',
);