<?php
/*Created by Кирилл (16.08.2018 19:44)*/

return array(
	'books'=>array(
		'level_1'=>'kirjat',
		'level_2'=>array(
			'categories'=>'kategoriat',
			'publishers'=>'kustantajat',
			'series'=>'sarjat',
			'authors'=>'tekijat',
			'bindings'=>'ulkoasu',
			'years'=>'vuodet',
		),
	),
	'sheetmusic'=>array(
		'level_1'=>'nuotit',
		'level_2'=>array(
			'categories'=>'kategoriat',
			'publishers'=>'kustantajat',
			'series'=>'sarjat',
			'authors'=>'tekijat',
			'bindings'=>'tuotteen-muoto',
			'years'=>'vuodet',
		),
	),
	'music'=>array(
		'level_1'=>'musiikki',
		'level_2'=>array(
			'categories'=>'kategoriat',
			'publishers'=>'levy-yhtiot',
			'series'=>'sarjat',
			'authors'=>'tekijat',
			'years'=>'vuodet',
			'performers'=>'esiintyjat',
			'media'=>'tuotteen-muoto',
		),
	),
	'soft'=>array(
		'level_1'=>'multimedia',
		'level_2'=>array(
			'categories'=>'luokat',
			'publishers'=>'kustantajat',
			'authors'=>'tekijat',
			'years'=>'vuodet',
			'media'=>'tuotteen-muoto',
		),
	),
	'periodics'=>array(
		'level_1'=>'lehtitilaus',
		'level_2'=>array(
			'categories'=>'luokat',
			'types'=>'julkaisutyyppi',
			'gift'=>'lahjaksi',
		),
	),
	'video'=>array(
		'level_1'=>'dvd-elokuvat',
		'level_2'=>array(
			'categories'=>'luokat',
			'years'=>'vuodet',
			'actors'=>'nayttelijat',
			'directors'=>'ohjaajat',
			'audiostreams'=>'aaniraidat',
			'subtitles'=>'tekstitysten-kieli',
			'media'=>'tuotteen-tyyppi',
			'yearreleases'=>'julkaisuvuosi',
		),
	),
	'printed'=>array(
		'level_1'=>'muut',
		'level_2'=>array(
			'categories'=>'kategoriat',
			'publishers'=>'valmistajat',
			'years'=>'vuodet',
		),
	),
	'maps'=>array(
		'level_1'=>'kartat',
		'level_2'=>array(
			'categories'=>'kategoriat',
			'publishers'=>'kustantajat',
			'bindings'=>'ulkoasu',
			'years'=>'vuodet',
		),
	),


	'sale'=>'alennusmyynti',
	'register'=>'rekisterointi',
	'login'=>'kirjaudu-sisaan',
	'cart'=>'ostoskori',
	'conditions'=>'kayttoehdot',
	'conditions_order'=>'kuinka-tehda-tilauksen',
	'conditions_subscription'=>'ehdot-tilaus-aikakauslehdet',
	'contact'=>'yhteystiedot',
	'legal_notice'=>'oikeudellinen-huomautus',
	'faq'=>'kysymys',
	'aboutus'=>'meista',
	'ourstore'=>'myymalamme',
	'csr'=>'vastuu',
	'offers_partners'=>'tarjoukset-jalleenmyyjille',
//	'thawte'=>'tietoa-thawtesta',
	'safety'=>'tietoa-maksujen-turvallisuudesta',
	'zone_info'=>'aluekoodi-5',
	'paypal'=>'mika-on-paypal',
	'sitemap'=>'sivustokartta',
	'me'=>'tili',
	'advsearch'=>'haku',


	'offers'=>'suosituksia',
	'for-firms'=>'erikoistarjouksia-yrityksille',
	'for-lib'=>'erikoistarjouksia-kirjastoille',
	'for-uni'=>'erikoistarjouksia-opettajille',
	'for-fs'=>'erikoistarjoukset-ilman-postikuluja',
	'for-alle2'=>'erikoistarjoukset-2-€',

	'bookshelf'=>'kirjahylly',
);